/* Generated By:JavaCC: Do not edit this line. AnalyzerConstants.java */
package proyecto1.XLSaXForm.Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIAR_AGRUPACION = 1;
  /** RegularExpression Id. */
  int FINALIZAR_AGRUPACION = 2;
  /** RegularExpression Id. */
  int INICIAR_CICLO = 3;
  /** RegularExpression Id. */
  int FINALIZAR_CICLO = 4;
  /** RegularExpression Id. */
  int TEXTO = 5;
  /** RegularExpression Id. */
  int FECHA = 6;
  /** RegularExpression Id. */
  int NOTA = 7;
  /** RegularExpression Id. */
  int ENTERO = 8;
  /** RegularExpression Id. */
  int RANGO = 9;
  /** RegularExpression Id. */
  int DECIMAL = 10;
  /** RegularExpression Id. */
  int HORA = 11;
  /** RegularExpression Id. */
  int FECHAHORA = 12;
  /** RegularExpression Id. */
  int CONDICIONAL = 13;
  /** RegularExpression Id. */
  int SELECCIONA_MULTIPLES = 14;
  /** RegularExpression Id. */
  int SELECCIONA_UNO = 15;
  /** RegularExpression Id. */
  int ID_PREGUNTA = 16;
  /** RegularExpression Id. */
  int ETIQUETA = 17;
  /** RegularExpression Id. */
  int PARAMETRO = 18;
  /** RegularExpression Id. */
  int CALCULAR = 19;
  /** RegularExpression Id. */
  int APLICABLE = 20;
  /** RegularExpression Id. */
  int SUGERENCIA = 21;
  /** RegularExpression Id. */
  int REQUERIDO = 22;
  /** RegularExpression Id. */
  int PORDEFECTO = 23;
  /** RegularExpression Id. */
  int REQUERIDOMSN = 24;
  /** RegularExpression Id. */
  int CODIGO_POST = 25;
  /** RegularExpression Id. */
  int CODIGO_PRE = 26;
  /** RegularExpression Id. */
  int RESTRINGIR = 27;
  /** RegularExpression Id. */
  int RESTRINGIRMSN = 28;
  /** RegularExpression Id. */
  int LECTURA = 29;
  /** RegularExpression Id. */
  int APARIENCIA = 30;
  /** RegularExpression Id. */
  int REPETICION = 31;
  /** RegularExpression Id. */
  int MULTIMEDIA = 32;
  /** RegularExpression Id. */
  int Igual = 33;
  /** RegularExpression Id. */
  int LlaveL = 34;
  /** RegularExpression Id. */
  int LlaveR = 35;
  /** RegularExpression Id. */
  int VALOR_C = 36;
  /** RegularExpression Id. */
  int NOMBRE = 37;
  /** RegularExpression Id. */
  int LETRA = 38;
  /** RegularExpression Id. */
  int NUM = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"INICIAR AGRUPACION\"",
    "\"FINALIZAR AGRUPACION\"",
    "\"INICIAR CICLO\"",
    "\"FINALIZAR CICLO\"",
    "\"TEXTO\"",
    "\"FECHA\"",
    "\"NOTA\"",
    "\"ENTERO\"",
    "\"RANGO\"",
    "\"DECIMAL\"",
    "\"HORA\"",
    "\"FECHAHORA\"",
    "\"CONDICIONAL\"",
    "\"SELECCIONA_MULTIPLES\"",
    "\"selecciona_uno\"",
    "\"IDPREGUNTA\"",
    "\"ETIQUETA\"",
    "\"PARAMETRO\"",
    "\"CALCULO\"",
    "\"APLICABLE\"",
    "\"SUGERIR\"",
    "\"REQUERIDO\"",
    "\"PREDETERMINADO\"",
    "\"REQUERIDOMSN\"",
    "\"CODIGO_POST\"",
    "\"CODIGO_PRE\"",
    "\"RESTRINGIR\"",
    "\"RESTRINGIRMSN\"",
    "\"LECTURA\"",
    "\"APARIENCIA\"",
    "\"REPETICION\"",
    "\"MULTIMEDIA\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "<VALOR_C>",
    "<NOMBRE>",
    "<LETRA>",
    "<NUM>",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
