/* Generated By:JavaCC: Do not edit this line. Analyzer.java */
  package proyecto1.XLSaXForm.Analizador;
  import proyecto1.XLSaXForm.Nodo;
  import proyecto1.XLSaXForm.Constants;
  public class Analyzer implements AnalyzerConstants {
  public Nodo root;

  final public void INICIO() throws ParseException {
  Nodo padre, hijo;
Token t;
    padre = new Nodo(Constants.INICIO,0,0,"INICIO");
    hijo = INSTRUCCIONES();
                         padre.hijos.add(hijo); root = padre;
    jj_consume_token(0);
  }

  final public Nodo INSTRUCCIONES() throws ParseException {
  Nodo padre,hijo;
    if (jj_2_2(2)) {
    padre = new Nodo("INSTRUCCIONES",0,0,"INSTRUCCIONES");
      label_1:
      while (true) {
        hijo = INICIAR();
                       padre.hijos.add(hijo);
        if (jj_2_1(2)) {
          ;
        } else {
          break label_1;
        }
      }
    {if (true) return padre;}
    } else if (jj_2_3(2)) {
      jj_consume_token(0);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo INICIAR() throws ParseException {
  Nodo padre,hijo;
    if (jj_2_4(2)) {
      padre = INICIARAGRUPACION();
                          {if (true) return padre;}
    } else if (jj_2_5(2)) {
      padre = INICIARCICLO();
                      {if (true) return padre;}
    } else if (jj_2_6(2)) {
      padre = PREGUNTA();
                  {if (true) return padre;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo INICIARAGRUPACION() throws ParseException {
 Nodo padre, hijo,hijo2;
    jj_consume_token(INICIAR_AGRUPACION);
                     padre=new Nodo(Constants.INICIARAGRUPACION,0,0,"INICIAR AGRUPACION");
    jj_consume_token(LlaveL);
    hijo = PARAMETROAGRUPACION();
    jj_consume_token(LlaveR);
    hijo2 = FINAGRUPACION();
                      padre.hijos.add(hijo);padre.hijos.add(hijo2); {if (true) return padre;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo FINAGRUPACION() throws ParseException {
 Nodo padre, hijo;
    if (jj_2_7(2)) {
      padre = INSTRUCCIONES();
      jj_consume_token(FINALIZAR_AGRUPACION);
      jj_consume_token(LlaveL);
      jj_consume_token(LlaveR);
                                                                {if (true) return padre;}
    } else if (jj_2_8(2)) {
      jj_consume_token(FINALIZAR_AGRUPACION);
      jj_consume_token(LlaveL);
      jj_consume_token(LlaveR);
                                          padre=new Nodo(""); {if (true) return padre;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo PARAMETROAGRUPACION() throws ParseException {
 Nodo padre, hijo;
Token t;
    jj_consume_token(ID_PREGUNTA);
               padre=new Nodo("ID PREGUNTA",0,0,"ID PREGUNTA");
    t = jj_consume_token(VALOR_C);
 String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
padre.hijos.add(hijo); {if (true) return padre;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo INICIARCICLO() throws ParseException {
 Nodo padre, hijo,hijo2;
    jj_consume_token(INICIAR_CICLO);
                padre=new Nodo(Constants.INICIARCICLO,0,0,"INICIAR CICLO");
    jj_consume_token(LlaveL);
    hijo = PARAMETROAGRUPACION();
    jj_consume_token(LlaveR);
    hijo2 = FINCICLO();
                 padre.hijos.add(hijo);padre.hijos.add(hijo2); {if (true) return padre;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo FINCICLO() throws ParseException {
 Nodo padre, hijo;
    if (jj_2_9(2)) {
      padre = INSTRUCCIONES();
      jj_consume_token(FINALIZAR_CICLO);
      jj_consume_token(LlaveL);
      jj_consume_token(LlaveR);
                                                           {if (true) return padre;}
    } else if (jj_2_10(2)) {
      jj_consume_token(FINALIZAR_CICLO);
      jj_consume_token(LlaveL);
      jj_consume_token(LlaveR);
                                     padre=new Nodo(""); {if (true) return padre;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo PREGUNTA() throws ParseException {
Nodo padre,hijo;
    if (jj_2_11(2)) {
      jj_consume_token(ENTERO);
          padre=new Nodo(Constants.ENTERO,0,0,"ENTERO");
      jj_consume_token(LlaveL);
      hijo = MUCHOS_CONTENIDOSP();
                                   padre.hijos.add(hijo);
      jj_consume_token(LlaveR);
                                                                     {if (true) return padre;}
    } else if (jj_2_12(2)) {
      jj_consume_token(NOTA);
             padre=new Nodo(Constants.NOTA,0,0,"NOTA");
      jj_consume_token(LlaveL);
      hijo = MUCHOS_CONTENIDOSP();
                                  padre.hijos.add(hijo);
      jj_consume_token(LlaveR);
                                                                    {if (true) return padre;}
    } else if (jj_2_13(2)) {
      jj_consume_token(FECHA);
              padre=new Nodo(Constants.FECHA,0,0,"FECHA");
      jj_consume_token(LlaveL);
      hijo = MUCHOS_CONTENIDOSP();
                                  padre.hijos.add(hijo);
      jj_consume_token(LlaveR);
                                                                    {if (true) return padre;}
    } else if (jj_2_14(2)) {
      jj_consume_token(TEXTO);
              padre=new Nodo(Constants.TEXTO,0,0,"TEXTO");
      jj_consume_token(LlaveL);
      hijo = MUCHOS_CONTENIDOSP();
                                  padre.hijos.add(hijo);
      jj_consume_token(LlaveR);
                                                                    {if (true) return padre;}
    } else if (jj_2_15(2)) {
      jj_consume_token(RANGO);
              padre=new Nodo(Constants.RANGO,0,0,"RANGO");
      jj_consume_token(LlaveL);
      hijo = MUCHOS_CONTENIDOSP();
                                  padre.hijos.add(hijo);
      jj_consume_token(LlaveR);
                                                                    {if (true) return padre;}
    } else if (jj_2_16(2)) {
      jj_consume_token(SELECCIONA_UNO);
      jj_consume_token(ELEGIR);
                               padre=new Nodo(Constants.SELECCIONA_UNO,0,0,"SELECCIONA_UNO");
      jj_consume_token(LlaveL);
      hijo = MUCHOS_CONTENIDOSP();
                                  padre.hijos.add(hijo);
      jj_consume_token(LlaveR);
                                                                    {if (true) return padre;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo MUCHOS_CONTENIDOSP() throws ParseException {
Nodo padre,hijo,hijo2;
    if (jj_2_18(2)) {
   padre = new Nodo("VALORES",0,0,"VALORES");
      label_2:
      while (true) {
        hijo = CONTENIDO_PREGUNTA();
                                 padre.hijos.add(hijo);
        if (jj_2_17(2)) {
          ;
        } else {
          break label_2;
        }
      }
 {if (true) return padre;}
    } else if (jj_2_19(2)) {
      jj_consume_token(0);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo CONTENIDO_PREGUNTA() throws ParseException {
Nodo padre,hijo;
Token t;
    if (jj_2_20(2)) {
      jj_consume_token(ID_PREGUNTA);
                   padre=new Nodo("ID PREGUNTA",0,0,"ID PREGUNTA");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~",""); hijo=new Nodo(Constants.IDPREGUNTA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_21(2)) {
      jj_consume_token(APLICABLE);
                  padre=new Nodo("APLICABLE",0,0,"APLICABLE");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~",""); hijo=new Nodo(Constants.APLICABLE, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_22(2)) {
      jj_consume_token(ETIQUETA);
                    padre=new Nodo("ETIQUETA",0,0,"ETIQUETA");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~",""); hijo=new Nodo(Constants.ETIQUETA, t.beginLine, t.beginColumn, aux.replace("\u005c"","")); padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_23(2)) {
      jj_consume_token(PARAMETRO);
                  padre=new Nodo("PARAMETRO",0,0,"PARAMETRO");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~",""); hijo=new Nodo(Constants.PARAMETRO, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_24(2)) {
      jj_consume_token(CALCULAR);
                 padre=new Nodo("CALCULAR",0,0,"CALCULAR");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.CALCULAR, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_25(2)) {
      jj_consume_token(SUGERENCIA);
                  padre=new Nodo("SUGERENCIA",0,0,"SUGERENCIA");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_26(2)) {
      jj_consume_token(REQUERIDO);
                  padre=new Nodo("REQUERIDO",0,0,"REQUERIDO");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_27(2)) {
      jj_consume_token(PORDEFECTO);
                   padre=new Nodo("PORDEFECTO",0,0,"PORDEFECTO");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_28(2)) {
      jj_consume_token(REQUERIDOMSN);
                     padre=new Nodo("REQUERIDOMSN",0,0,"REQUERIDOMSN");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_29(2)) {
      jj_consume_token(CODIGO_POST);
                    padre=new Nodo("CODIGO_POST",0,0,"CODIGO_POST");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_30(2)) {
      jj_consume_token(CODIGO_PRE);
                   padre=new Nodo("CODIGO_PRE",0,0,"CODIGO_PRE");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_31(2)) {
      jj_consume_token(RESTRINGIR);
                   padre=new Nodo("RESTRINGIR",0,0,"RESTRINGIR");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_32(2)) {
      jj_consume_token(RESTRINGIRMSN);
                      padre=new Nodo("RESTRINGIRMSN",0,0,"RESTRINGIRMSN");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_33(2)) {
      jj_consume_token(LECTURA);
                padre=new Nodo("LECTURA",0,0,"LECTURA");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_34(2)) {
      jj_consume_token(APARIENCIA);
                   padre=new Nodo("APARIENCIA",0,0,"APARIENCIA");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_35(2)) {
      jj_consume_token(REPETICION);
                   padre=new Nodo("REPETICION",0,0,"REPETICION");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else if (jj_2_36(2)) {
      jj_consume_token(MULTIMEDIA);
                   padre=new Nodo("MULTIMEDIA",0,0,"MULTIMEDIA");
      t = jj_consume_token(VALOR_C);
      String aux=t.image.replace("#",""); aux=aux.replace("~","");  hijo=new Nodo(Constants.SUGERENCIA, t.beginLine, t.beginColumn, aux.replace("\u005c"",""));
     padre.hijos.add(hijo); {if (true) return padre;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  private boolean jj_3_24() {
    if (jj_scan_token(CALCULAR)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3R_3() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3_22() {
    if (jj_scan_token(ETIQUETA)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_23() {
    if (jj_scan_token(PARAMETRO)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3_21() {
    if (jj_scan_token(APLICABLE)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3R_7() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) return true;
    }
    return false;
  }

  private boolean jj_3_2() {
    Token xsp;
    if (jj_3_1()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_1()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) {
    jj_scanpos = xsp;
    if (jj_3_24()) {
    jj_scanpos = xsp;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) {
    jj_scanpos = xsp;
    if (jj_3_27()) {
    jj_scanpos = xsp;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) {
    jj_scanpos = xsp;
    if (jj_3_30()) {
    jj_scanpos = xsp;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_32()) {
    jj_scanpos = xsp;
    if (jj_3_33()) {
    jj_scanpos = xsp;
    if (jj_3_34()) {
    jj_scanpos = xsp;
    if (jj_3_35()) {
    jj_scanpos = xsp;
    if (jj_3_36()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_20() {
    if (jj_scan_token(ID_PREGUNTA)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  private boolean jj_3_18() {
    Token xsp;
    if (jj_3_17()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_17()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_16() {
    if (jj_scan_token(SELECCIONA_UNO)) return true;
    if (jj_scan_token(ELEGIR)) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_scan_token(RANGO)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(TEXTO)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(FECHA)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(NOTA)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3R_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(ENTERO)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(FINALIZAR_CICLO)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(FINALIZAR_CICLO)) return true;
    return false;
  }

  private boolean jj_3_36() {
    if (jj_scan_token(MULTIMEDIA)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3R_5() {
    if (jj_scan_token(INICIAR_CICLO)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_35() {
    if (jj_scan_token(REPETICION)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_34() {
    if (jj_scan_token(APARIENCIA)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_33() {
    if (jj_scan_token(LECTURA)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_32() {
    if (jj_scan_token(RESTRINGIRMSN)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_31() {
    if (jj_scan_token(RESTRINGIR)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(FINALIZAR_AGRUPACION)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_30() {
    if (jj_scan_token(CODIGO_PRE)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(FINALIZAR_AGRUPACION)) return true;
    return false;
  }

  private boolean jj_3_29() {
    if (jj_scan_token(CODIGO_POST)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_28() {
    if (jj_scan_token(REQUERIDOMSN)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_27() {
    if (jj_scan_token(PORDEFECTO)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3R_4() {
    if (jj_scan_token(INICIAR_AGRUPACION)) return true;
    if (jj_scan_token(LlaveL)) return true;
    return false;
  }

  private boolean jj_3_26() {
    if (jj_scan_token(REQUERIDO)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_scan_token(SUGERENCIA)) return true;
    if (jj_scan_token(VALOR_C)) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_5()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public AnalyzerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[36];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Analyzer(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Analyzer(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new AnalyzerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Analyzer(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AnalyzerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Analyzer(AnalyzerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(AnalyzerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[39];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 39; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 36; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
