/* Generated By:JavaCC: Do not edit this line. AnalyzerTokenManager.java */
package proyecto1.XLSaXForm.Analizador;
import proyecto1.XLSaXForm.Nodo;
import proyecto1.XLSaXForm.Constants;

/** Token Manager. */
public class AnalyzerTokenManager implements AnalyzerConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1ffdfbfeL) != 0L)
            return 8;
         if ((active0 & 0x20000L) != 0L)
            return 22;
         return -1;
      case 1:
         if ((active0 & 0x1ffffbfeL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 8;
         }
         return -1;
      case 2:
         if ((active0 & 0x1ffffbfeL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 8;
         }
         return -1;
      case 3:
         if ((active0 & 0x1ffffb7eL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 3;
            return 8;
         }
         if ((active0 & 0x80L) != 0L)
            return 8;
         return -1;
      case 4:
         if ((active0 & 0x1ffff91eL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 8;
         }
         if ((active0 & 0x260L) != 0L)
            return 8;
         return -1;
      case 5:
         if ((active0 & 0x1ffff01eL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
            return 8;
         }
         if ((active0 & 0x900L) != 0L)
            return 8;
         return -1;
      case 6:
         if ((active0 & 0x1d9ff01eL) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 6;
            return 8;
         }
         if ((active0 & 0x2000000L) != 0L)
            return 8;
         if ((active0 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0xa000L) != 0L)
            return 8;
         if ((active0 & 0x1d9f5014L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 7;
            return 8;
         }
         if ((active0 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x1d8a1014L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return 8;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x154000L) != 0L)
            return 8;
         if ((active0 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 9;
            }
            return 8;
         }
         if ((active0 & 0x1d8a1000L) != 0L)
            return 8;
         if ((active0 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x1100000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 10;
            return 8;
         }
         return -1;
      case 11:
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x100000L) != 0L)
            return 8;
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 11;
            return 8;
         }
         return -1;
      case 12:
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x1000000L) != 0L)
            return 8;
         return -1;
      case 13:
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 18:
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 8;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 61:
         return jjStopAtPos(0, 29);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x4010000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x608000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2900L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x54L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x100aL);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x84000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x9940200L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 123:
         return jjStopAtPos(0, 30);
      case 125:
         return jjStopAtPos(0, 31);
      default :
         return jjMoveNfa_0(6, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0xc200L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xb940060L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x14L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x800L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x10aL);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x680080L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x4010000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x10020000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000040L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x200aL);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x10018000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x214L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x8001000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x140000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x84000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x1800000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x180L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 7, 8);
         return jjMoveStringLiteralDfa4_0(active0, 0x4014L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x800aL);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x8020100L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0xa00L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x610000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x4001000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x13800020L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x140000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 8);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x1c1000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x600000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1400080aL);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x14L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 79:
      case 111:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 5, 8);
         else if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 8);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x1820100L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200a000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000aL);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x4026000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x9800014L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      case 79:
      case 111:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 8, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x600000L);
      case 82:
      case 114:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 11, 8);
         return jjMoveStringLiteralDfa6_0(active0, 0x2140000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x600000L);
      case 65:
      case 97:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(6, 25, 8);
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x10080000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x140000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x5820000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0xaL);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x6000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa7_0(active0, 0x14L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0xaL);
      case 65:
      case 97:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 8);
         return jjMoveStringLiteralDfa8_0(active0, 0x14L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x40a0000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x10140000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x600000L);
      case 82:
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 15, 8);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x2L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x8L);
      case 69:
      case 101:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(8, 16, 8);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x15820000L);
      case 79:
      case 111:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(8, 14, 8);
         else if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x8300000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x400014L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x81000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0x14L);
      case 65:
      case 97:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(9, 12, 8);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(9, 17, 8);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(9, 26, 8);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(9, 28, 8);
         break;
      case 69:
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(9, 22);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x2L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000L);
      case 78:
      case 110:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(9, 27, 8);
         break;
      case 79:
      case 111:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(9, 19, 8);
         break;
      case 82:
      case 114:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x4L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x18L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x2L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000L);
      case 84:
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(10, 21);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 71:
      case 103:
         return jjMoveStringLiteralDfa12_0(active0, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x10L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x8L);
      case 78:
      case 110:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(11, 20, 8);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa12_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x10L);
      case 78:
      case 110:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(12, 24, 8);
         break;
      case 79:
      case 111:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(12, 3);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa13_0(active0, 0x2L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x2L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa14_0(active0, 0x10L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0x2L);
      case 79:
      case 111:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(14, 4);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa15_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa16_0(active0, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa17_0(active0, 0x4L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa17_0(active0, 0x2L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa18_0(active0, 0x4L);
      case 78:
      case 110:
         if ((active0 & 0x2L) != 0L)
            return jjStopAtPos(17, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa19_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(19, 2);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 35;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 22:
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(8);
                  break;
               case 1:
                  jjAddStates(0, 1);
                  break;
               case 3:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 5:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 22:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(8);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(8);
                  else if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 5;
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(2, 3);
                  break;
               case 0:
                  if (curChar == 126)
                     jjCheckNAddTwoStates(1, 4);
                  break;
               case 1:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(1, 4);
                  break;
               case 2:
                  if (curChar == 126 && kind > 32)
                     kind = 32;
                  break;
               case 4:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 7:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(8);
                  break;
               case 9:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(2, 3);
                  break;
               case 10:
                  if ((0x800000008000L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 11:
               case 23:
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(10);
                  break;
               case 12:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 24:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 35 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   1, 4, 22, 34, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, "\75", "\173", "\175", null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffffL, 
};
static final long[] jjtoSkip = {
   0xf000000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[35];
private final int[] jjstateSet = new int[70];
protected char curChar;
/** Constructor. */
public AnalyzerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public AnalyzerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 35; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
