/* Generated By:JavaCC: Do not edit this line. AnalyzerConstants.java */
package proyecto1.XLSaXForm.Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIAR_AGRUPACION = 1;
  /** RegularExpression Id. */
  int FINALIZAR_AGRUPACION = 2;
  /** RegularExpression Id. */
  int INICIAR_CICLO = 3;
  /** RegularExpression Id. */
  int FINALIZAR_CICLO = 4;
  /** RegularExpression Id. */
  int TEXTO = 5;
  /** RegularExpression Id. */
  int FECHA = 6;
  /** RegularExpression Id. */
  int NOTA = 7;
  /** RegularExpression Id. */
  int ENTERO = 8;
  /** RegularExpression Id. */
  int RANGO = 9;
  /** RegularExpression Id. */
  int SELECCIONA_UNO = 10;
  /** RegularExpression Id. */
  int ID_PREGUNTA = 11;
  /** RegularExpression Id. */
  int ETIQUETA = 12;
  /** RegularExpression Id. */
  int PARAMETRO = 13;
  /** RegularExpression Id. */
  int CALCULAR = 14;
  /** RegularExpression Id. */
  int APLICABLE = 15;
  /** RegularExpression Id. */
  int SUGERENCIA = 16;
  /** RegularExpression Id. */
  int REQUERIDO = 17;
  /** RegularExpression Id. */
  int PORDEFECTO = 18;
  /** RegularExpression Id. */
  int REQUERIDOMSN = 19;
  /** RegularExpression Id. */
  int CODIGO_POST = 20;
  /** RegularExpression Id. */
  int CODIGO_PRE = 21;
  /** RegularExpression Id. */
  int RESTRINGIR = 22;
  /** RegularExpression Id. */
  int RESTRINGIRMSN = 23;
  /** RegularExpression Id. */
  int LECTURA = 24;
  /** RegularExpression Id. */
  int APARIENCIA = 25;
  /** RegularExpression Id. */
  int REPETICION = 26;
  /** RegularExpression Id. */
  int MULTIMEDIA = 27;
  /** RegularExpression Id. */
  int Igual = 28;
  /** RegularExpression Id. */
  int LlaveL = 29;
  /** RegularExpression Id. */
  int LlaveR = 30;
  /** RegularExpression Id. */
  int VALOR_C = 31;
  /** RegularExpression Id. */
  int NOMBRE = 32;
  /** RegularExpression Id. */
  int LETRA = 33;
  /** RegularExpression Id. */
  int NUM = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"INICIAR AGRUPACION\"",
    "\"FINALIZAR AGRUPACION\"",
    "\"INICIAR CICLO\"",
    "\"FINALIZAR CICLO\"",
    "\"TEXTO\"",
    "\"FECHA\"",
    "\"NOTA\"",
    "\"ENTERO\"",
    "\"RANGO\"",
    "\"selecciona_uno\"",
    "\"IDPREGUNTA\"",
    "\"ETIQUETA\"",
    "\"PARAMETRO\"",
    "\"CALCULAR\"",
    "\"APLICABLE\"",
    "\"SUGERENCIA\"",
    "\"REQUERIDO\"",
    "\"PORDEFECTO\"",
    "\"REQUERIDOMSN\"",
    "\"CODIGO_POST\"",
    "\"CODIGO_PRE\"",
    "\"RESTRINGIR\"",
    "\"RESTRINGIRMSN\"",
    "\"LECTURA\"",
    "\"APARIENCIA\"",
    "\"REPETICION\"",
    "\"MULTIMEDIA\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "<VALOR_C>",
    "<NOMBRE>",
    "<LETRA>",
    "<NUM>",
    "\"\\n\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
