/* Generated By:JavaCC: Do not edit this line. ConfiguracionesConstants.java */
package proyecto1.Config.Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConfiguracionesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DELIM = 5;
  /** RegularExpression Id. */
  int TituloForm = 6;
  /** RegularExpression Id. */
  int IdForm = 7;
  /** RegularExpression Id. */
  int Estilo = 8;
  /** RegularExpression Id. */
  int Importar = 9;
  /** RegularExpression Id. */
  int CodigoPrincipal = 10;
  /** RegularExpression Id. */
  int CodigoGlobal = 11;
  /** RegularExpression Id. */
  int Fila = 12;
  /** RegularExpression Id. */
  int LlaveL = 13;
  /** RegularExpression Id. */
  int LlaveR = 14;
  /** RegularExpression Id. */
  int Cadena = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int AceptarCualquier = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "\"`\"",
    "\"titulo_formulario\"",
    "\"idform\"",
    "\"estilo\"",
    "\"importar\"",
    "\"codigo_principal\"",
    "\"codigo_global\"",
    "\"Fila\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 15>",
    "\"~\"",
  };

}
