/* Generated By:JavaCC: Do not edit this line. AnalyzerTokenManager.java */
package proyecto1.Encuesta.Analizador;
import proyecto1.Encuesta.Nodo;
import proyecto1.Encuesta.Constants;

/** Token Manager. */
public class AnalyzerTokenManager implements AnalyzerConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1fffffffeL) != 0L)
         {
            jjmatchedKind = 37;
            return 0;
         }
         return -1;
      case 1:
         if ((active0 & 0x1fffffffeL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 1;
            return 0;
         }
         return -1;
      case 2:
         if ((active0 & 0x1fffffffeL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 2;
            return 0;
         }
         return -1;
      case 3:
         if ((active0 & 0x880L) != 0L)
            return 0;
         if ((active0 & 0x1fffff77eL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 3;
            return 0;
         }
         return -1;
      case 4:
         if ((active0 & 0x1260L) != 0L)
            return 0;
         if ((active0 & 0x1ffffe51eL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 4;
            }
            return 0;
         }
         return -1;
      case 5:
         if ((active0 & 0x100L) != 0L)
            return 0;
         if ((active0 & 0x1fffff41eL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 5;
            return 0;
         }
         return -1;
      case 6:
         if ((active0 & 0x20280400L) != 0L)
            return 0;
         if ((active0 & 0x1dfd7f01eL) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 6;
            return 0;
         }
         return -1;
      case 7:
         if ((active0 & 0x20000L) != 0L)
            return 0;
         if ((active0 & 0x1dfd5f014L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 7;
            return 0;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x1541000L) != 0L)
            return 0;
         if ((active0 & 0x1de81e014L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return 0;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x1dc010000L) != 0L)
            return 0;
         if ((active0 & 0x380e000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 9;
            }
            return 0;
         }
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x2002000L) != 0L)
            return 0;
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x1180c000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 10;
            return 0;
         }
         return -1;
      case 11:
         if ((active0 & 0x1000000L) != 0L)
            return 0;
         if ((active0 & 0x1080c000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 11;
            return 0;
         }
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x10000000L) != 0L)
            return 0;
         if ((active0 & 0x80c000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 12;
            return 0;
         }
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xaL) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x808000L) != 0L)
            return 0;
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 13;
            return 0;
         }
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 14;
            return 0;
         }
         if ((active0 & 0x14L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 15:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 15;
            return 0;
         }
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 16:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 16;
            return 0;
         }
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 17:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 17;
            return 0;
         }
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x2L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 18:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 18;
            return 0;
         }
         if ((active0 & 0x4L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 37;
               jjmatchedPos = 8;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 35:
         return jjStopAtPos(0, 38);
      case 46:
         jjmatchedKind = 44;
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 61:
         return jjStopAtPos(0, 34);
      case 91:
         return jjStopAtPos(0, 39);
      case 93:
         return jjStopAtPos(0, 40);
      case 96:
         return jjStopAtPos(0, 33);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x40100000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x6082000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x20100L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1054L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1000aL);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x840000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x99400200L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x20c000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 123:
         return jjStopAtPos(0, 35);
      case 125:
         return jjStopAtPos(0, 36);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 45);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0xc0200L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xb940d460L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x14L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x10aL);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x6002880L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x40100000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x100200000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x20001440L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x6000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000aL);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x10018c000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2214L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x80010000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x1400000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x40800L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x18000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x180L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 7, 0);
         else if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 0);
         return jjMoveStringLiteralDfa4_0(active0, 0x40014L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000aL);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x802000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x8020c100L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x1040L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x6100400L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x40010000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x138000020L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1400000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 6;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x10c000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x1c10000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x6000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x14000200aL);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x14L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x40400L);
      case 79:
      case 111:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 5, 0);
         else if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 0);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x18200100L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200a0000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x10040aL);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0xe000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x40060000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x98200014L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 79:
      case 111:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(5, 8, 0);
         return jjMoveStringLiteralDfa6_0(active0, 0x6000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x21400000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x6000000L);
      case 65:
      case 97:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(6, 29, 0);
         break;
      case 66:
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x100800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x140e000L);
      case 76:
      case 108:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(6, 10, 0);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x58000000L);
      case 79:
      case 111:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 0);
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 82:
      case 114:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 0);
         return jjMoveStringLiteralDfa7_0(active0, 0xaL);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x60000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa7_0(active0, 0x14L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0xaL);
      case 65:
      case 97:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 17, 0);
         return jjMoveStringLiteralDfa8_0(active0, 0x14L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x101400000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x18000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0xe000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x6000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x841000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(8, 12, 0);
         return jjMoveStringLiteralDfa9_0(active0, 0x2L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x8L);
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(8, 20, 0);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x158000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0xe000L);
      case 79:
      case 111:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 18, 0);
         else if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x83000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000014L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0x14L);
      case 65:
      case 97:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(9, 16, 0);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(9, 30, 0);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(9, 32, 0);
         return jjMoveStringLiteralDfa10_0(active0, 0xe000L);
      case 69:
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(9, 26, 0);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x2L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x800008L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000L);
      case 78:
      case 110:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(9, 31, 0);
         break;
      case 82:
      case 114:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa11_0(active0, 0xc000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x4L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x18L);
      case 76:
      case 108:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(10, 13, 0);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x800000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x2L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000L);
      case 84:
      case 116:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(10, 25, 0);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x800000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa12_0(active0, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x10L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0x4000L);
      case 78:
      case 110:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(11, 24, 0);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa12_0(active0, 0x8002L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x10L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa13_0(active0, 0x800000L);
      case 78:
      case 110:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(12, 28, 0);
         return jjMoveStringLiteralDfa13_0(active0, 0x8000L);
      case 79:
      case 111:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(12, 3);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa13_0(active0, 0x2L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa13_0(active0, 0x4L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa13_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x2L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa14_0(active0, 0x4010L);
      case 79:
      case 111:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(13, 15, 0);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(13, 23, 0);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa15_0(active0, 0x2L);
      case 79:
      case 111:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(14, 4);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa15_0(active0, 0x4L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa15_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa16_0(active0, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x4002L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa17_0(active0, 0x4L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa17_0(active0, 0x2L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa17_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa18_0(active0, 0x4L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa18_0(active0, 0x4000L);
      case 78:
      case 110:
         if ((active0 & 0x2L) != 0L)
            return jjStopAtPos(17, 1);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa19_0(active0, 0x4000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa19_0(active0, 0x4L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(19, 2);
         break;
      case 83:
      case 115:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(19, 14, 0);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 4;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 37)
                     kind = 37;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0xffffbff7ffffffffL & l) != 0L)
                     jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 37)
                        kind = 37;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 126)
                     jjCheckNAdd(2);
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 37)
                     kind = 37;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0xbfffffffd7ffffffL & l) != 0L)
                     jjCheckNAddTwoStates(2, 3);
                  break;
               case 3:
                  if (curChar == 126 && kind > 43)
                     kind = 43;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 4 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   2, 3, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, "\140", "\75", "\173", "\175", null, "\43", 
"\133", "\135", null, null, null, "\56", "\56\56", null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x39ffffffffffL, 
};
static final long[] jjtoSkip = {
   0x3c00000000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[4];
private final int[] jjstateSet = new int[8];
protected char curChar;
/** Constructor. */
public AnalyzerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public AnalyzerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 4; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
